### ISSUE TITLE
Set a default storage class for PV/PVCs to function correctly

### ISSUE THREAD

**Issue by pfisterer** [infraly/k8s-on-openstack#52]
Hi all, 
Do you think it makes sense to (optionally) define a default storage class for dynamically creating OpenStack volumes to work out of the box?

Currently, after creating the cluster, I've used the following YAML-file to set the [DefaultStorageClass](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#lifecycle-of-a-volume-and-claim) for dynamic provisioning to work:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-default-class
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/cinder
parameters:
  availability: nova
```
The documentation also states the following:

> To enable dynamic storage provisioning based on storage class, the cluster administrator needs to **enable the DefaultStorageClass admission controller on the API server**. This can be done, for example, by ensuring that DefaultStorageClass is among the comma-delimited, ordered list of values for the --enable-admission-plugins flag of the API server component. For more information on API server command line flags, please check kube-apiserver documentation.

This is sth that should be checked in `files/kubeadm-init.yaml.j2`. 

```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
apiServerExtraArgs:
  enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,DefaultStorageClass, etc.
```

Sorry for spamming you with issues and PRs - I'm currently trying to get everything to work.

Best,
Dennis
